// <auto-generated />
using BlackLotus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackLotus.Migrations
{
    [DbContext(typeof(AppDBContex))]
    [Migration("20220929134352_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlackLotus.Model.Flower", b =>
                {
                    b.Property<int>("flowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("flowerId"), 1L, 1);

                    b.Property<string>("flowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("flowerId");

                    b.ToTable("flower", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
